# Generated by Django 3.1.3 on 2020-12-05 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20201205_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_vip',
        ),
    ]
